
/*! \file hashstrings.h
\brief Static hash strings

Statically hashed strings generated by the hashify tool from input file hashstrings.txt */

/*!
\def HASH_FOUNDATION
\details Hash of "foundation"

\def HASH_DEFAULT
\details Hash of "default"

\def HASH_TRUE
\details Hash of "true"

\def HASH_FALSE
\details Hash of "false"

\def HASH_LOCALE
\details Hash of "locale"

\def HASH_APPLICATION
\details Hash of "application"

\def HASH_USER
\details Hash of "user"

\def HASH_DAEMON
\details Hash of "daemon"

\def HASH_MEMORY
\details Hash of "memory"

\def HASH_TEMPORARY_MEMORY
\details Hash of "temporary_memory"

\def HASH_MEMORY_TRACKER
\details Hash of "memory_tracker"

\def HASH_LOCAL
\details Hash of "local"

\def HASH_REMOTE
\details Hash of "remote"

\def HASH_NONE
\details Hash of "none"

\def HASH_TEST
\details Hash of "test"

\def HASH_STREAM
\details Hash of "stream"

\def HASH_STRING
\details Hash of "string"

\def HASH_BENCHMARK
\details Hash of "benchmark"

\def HASH_TOOL
\details Hash of "tool"

\def HASH_CONFIG
\details Hash of "config"

\def HASH_ENVIRONMENT
\details Hash of "environment"

\def HASH_EXECUTABLE_NAME
\details Hash of "executable_name"

\def HASH_EXECUTABLE_DIRECTORY
\details Hash of "executable_directory"

\def HASH_EXECUTABLE_PATH
\details Hash of "executable_path"

\def HASH_INITIAL_WORKING_DIRECTORY
\details Hash of "initial_working_directory"

\def HASH_CURRENT_WORKING_DIRECTORY
\details Hash of "current_working_directory"

\def HASH_APPLICATION_DIRECTORY
\details Hash of "application_directory"

\def HASH_TEMPORARY_DIRECTORY
\details Hash of "temporary_directory"

\def HASH_SYSTEM
\details Hash of "system"

\def HASH_DEBUG
\details Hash of "debug"

\def HASH_FS
\details Hash of "fs"
*/

#pragma once

#include <foundation/hash.h>

/* ****** AUTOMATICALLY GENERATED, DO NOT EDIT ******
    Edit corresponding definitions file and rerun
    the foundation hashify tool to update this file */

#define HASH_FOUNDATION static_hash_string("foundation", 10, 0x13f0d2e482a6eaadULL)
#define HASH_DEFAULT static_hash_string("default", 7, 0xe1c3a22ea1763f7bULL)
#define HASH_TRUE static_hash_string("true", 4, 0x89a73a33420257f5ULL)
#define HASH_FALSE static_hash_string("false", 5, 0xc095fcfff8bca4abULL)
#define HASH_LOCALE static_hash_string("locale", 6, 0xfb3833132a868037ULL)
#define HASH_APPLICATION static_hash_string("application", 11, 0x1d0a3207798c58baULL)
#define HASH_USER static_hash_string("user", 4, 0x921c12dbd6f624f6ULL)
#define HASH_DAEMON static_hash_string("daemon", 6, 0x27b6055e22f461b7ULL)
#define HASH_MEMORY static_hash_string("memory", 6, 0x1ef05c31f30b3115ULL)
#define HASH_TEMPORARY_MEMORY static_hash_string("temporary_memory", 16, 0x99a81dcbf3f5c346ULL)
#define HASH_MEMORY_TRACKER static_hash_string("memory_tracker", 14, 0x344315811a5c41deULL)
#define HASH_LOCAL static_hash_string("local", 5, 0xd17754fcf40a2974ULL)
#define HASH_REMOTE static_hash_string("remote", 6, 0x4d4ee1b3734e2c5cULL)
#define HASH_NONE static_hash_string("none", 4, 0xa90768116f8af366ULL)
#define HASH_TEST static_hash_string("test", 4, 0x74326336c500c367ULL)
#define HASH_STREAM static_hash_string("stream", 6, 0x5798159f6f1f8b05ULL)
#define HASH_STRING static_hash_string("string", 6, 0xa1cc1854ea614cb4ULL)
#define HASH_BENCHMARK static_hash_string("benchmark", 9, 0xf06a63ae2ff7eaceULL)
#define HASH_TOOL static_hash_string("tool", 4, 0x4a8e770cf21d0529ULL)
#define HASH_CONFIG static_hash_string("config", 6, 0x336f91cbb8948a62ULL)
#define HASH_ENVIRONMENT static_hash_string("environment", 11, 0xaeb8326060894683ULL)
#define HASH_EXECUTABLE_NAME static_hash_string("executable_name", 15, 0xe04d18727d6aa0dfULL)
#define HASH_EXECUTABLE_DIRECTORY static_hash_string("executable_directory", 20, 0xb957eadb0ae3f969ULL)
#define HASH_EXECUTABLE_PATH static_hash_string("executable_path", 15, 0xcdae3cb1dc4a5d81ULL)
#define HASH_INITIAL_WORKING_DIRECTORY static_hash_string("initial_working_directory", 25, 0x8f4d99e8f8ae0e18ULL)
#define HASH_CURRENT_WORKING_DIRECTORY static_hash_string("current_working_directory", 25, 0x6b80ceb3924e8af3ULL)
#define HASH_APPLICATION_DIRECTORY static_hash_string("application_directory", 21, 0xbc4f42e916943280ULL)
#define HASH_TEMPORARY_DIRECTORY static_hash_string("temporary_directory", 19, 0xb75730bc0dd1d067ULL)
#define HASH_SYSTEM static_hash_string("system", 6, 0xb72020e83e0eb654ULL)
#define HASH_DEBUG static_hash_string("debug", 5, 0x71626bc355dbf213ULL)
#define HASH_FS static_hash_string("fs", 2, 0x4692a53ac19eddeeULL)
#define HASH_SOURCE static_hash_string("source", 6, 0x2154da52f04042d3ULL)
#define HASH_EVENT static_hash_string("event", 5, 0x9af1e926101c32dbULL)
#define HASH_VERSION static_hash_string("version", 7, 0x8cc092bba4f17f67ULL)
